graph LR;
	subgraph Server
		A[Create Socket] --> B[Bind to Address]
		B --> C[Listen for Connections]
		C --> D[Accept Connection]
		D --> E[Receive Data]
		E --> F[Send Data]
		F --> G[Close Connection]
	end

	subgraph Client
		H[Create Socket] --> I[Connect to Server]
		I --> J[Send Data]
		J --> K[Receive Data]
		K --> L[Close Connection]
	end

	H -.-> B
	J -.-> E
	K -.-> F
